version: "3.9"

services:
   api:
      build:
        context: .
        dockerfile: ./docker/local/django/Dockerfile
      command: /start
      volumes:
         - .:/app
         - static_volume:/app/staticfiles
      expose:
         -  "8000"
      env_file:
         - .env
      depends_on:
         - postgres-db
      networks:
         - hello-home

   # postgres database service
   postgres-db:
      image: postgres:12.0-alpine
      ports:
         - "5432:5432"
      # volumes here is for persistent storage
      volumes:
         - postgres_data_h:/var/lib/postgresql/data/
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      networks:
         - hello-home

#   nginx server
   nginx:
      restart: always
      depends_on:
         -  api
      volumes:
         - static_volume:/app/staticfiles
      build:
         context: ./docker/local/nginx
         dockerfile: Dockerfile
      ports:
         -  "8080:80"
      networks:
         - hello-home

#all services should be networked with the same name,using the bridge
networks:
   hello-home:
      driver: bridge

volumes:
   postgres_data_h:
   static_volume:
